### ISSUE TITLE
Feature idea: Enable / disable in admin

### ISSUE THREAD

**Issue by xeraa** [frankmullenger/silverstripe-underconstruction#1]
Drupal has a pretty similar feature where you can put your site into maintenance mode via the admin interface.
You could add a flag to site config for this module so one wouldn't have to fiddle with the module to enable or disable it. Hence this module could also be used during maintenance / scheduled down-time.

This would add a DB query when the module is disabled and waiting to be activated - which probably won't make any real difference.

**Comment by frankmullenger** [comment]
Cheers, I have added this feature now so you can turn on/off in the SiteConfig->Access tab:
https://github.com/frankmullenger/silverstripe-underconstruction/commit/f24d5b945b804936826b6c0ffccf9b876bfa7cd4

**Comment by xeraa** [comment]
Awesome, thanks!
